@startuml diagramaDeClasesControladores.
!theme reddress-darkblue

class ControladorCargaColaboraciones {
    - personaHumanaServices: IPersonaHumanaServices
    - documentoServices: IDocumentoServices
    + cargarColaboraciones(usuario: Usuario, dataCSV: File): void
}

@enduml