@startuml diagramaDeClasesRepositorios.
!theme reddress-darkblue

class RepositorioPersonaHumana {
    + guardar(persona: PersonaHumana): void
    + actualizar(persona: PersonaHumana): void
    + buscarPorDocumento(documentoId: Long): PersonaHumana
    + listar(): List<PersonaHumana>
}

class RepositorioPermisos {
    + guardar(permiso: Permiso): void
    + buscar(nombre: String): Permiso
}

class RepositorioOfertaCanjeada {
    + guardar(ofertaCanjeada: OfertaCanjeada): void
    + buscarPorFecha(fecha: LocalDate): List<OfertaCanjeada>
}

class RepositorioOferta {
    + guardar(oferta: Oferta): void
    + actualizar(oferta: Oferta): void
}

class RepositorioDocumento {
    + guardar(documento: Documento): void
    + buscar(id: Long): Documento
    + buscarPorNro(tipo: TipoDocumento, nro: String): Documento
}

@enduml