@startuml diagramaDespliegueActual.
node "Server AWS" {
    [Servidor de Aplicación] --> "  "
    database "MySQL"
    "MySQL" - "  "
    [Observabilidad]
}

node "Usuarios" {
    [Navegador web]
}

node "Heladeras" {
    [Sensor]
}

node "Mail Server" {
    [SMTP Server]
}

[Servidor de Aplicación] ..> "HTTP" [Navegador web]
[Navegador web] ..> "HTTP" [Servidor de Aplicación]

[Servidor de Aplicación] .up.> "SMTP" [SMTP Server]
[Servidor de Aplicación] --> "-"
[SMTP Server] -left- "-"

[Sensor] - "     "
[Servidor de Aplicación] -left-> "       "
"Server AWS" ..> "MQTT" "Heladeras"
@enduml